# Generated by Django 3.2.8 on 2021-10-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=4)),
                ('projectName', models.CharField(max_length=225)),
                ('uploadedBy', models.CharField(max_length=100)),
                ('subDate', models.DateField(null=True)),
            ],
        ),
    ]
